name: scaffold_core
description: An application-agnostic core library for Flutter/Dart apps.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  mmkv: ^2.4.0
  uni_links: ^0.5.1
